version: "2"
services:
 application:
    image: ${IMAGE_NAME}
    container_name: creditcard_fault_detection
    ports:
      - "80:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - BUCKET_NAME=${BUCKET_NAME}